# Generated by Django 5.0.4 on 2024-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaday_app', '0011_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('msg', models.CharField(max_length=300)),
            ],
        ),
    ]
